<?xml version="1.0" encoding="utf-8"?><Database Name="DXDB" Class="DbClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=DXDB;User ID=sa" SettingsObjectName="web1.Properties.Settings" SettingsPropertyName="SQLConnString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.assets" Member="assets">
    <Type Name="assets">
      <Column Name="AssetId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="First" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Last" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IC" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TagMacAddress" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="BatteryState" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PowerLowTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OutTIme" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InMineTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OutMineTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GasDensity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassTypeId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsValid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Show" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnchorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JobFunctionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Z" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LastInMineTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastOutMineTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DXAdmin" Member="DXAdmin">
    <Type Name="DXAdmin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pwd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="isAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DXLb" Member="DXLb">
    <Type Name="DXLb">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LbName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DXMember" Member="DXMember">
    <Type Name="DXMember">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pwd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Regions" Member="Regions">
    <Type Name="Regions">
      <Column Name="RegionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PerNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="HashPassword" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DXProd" Member="DXProd">
    <Type Name="DXProd">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lbid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Body" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Price2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Price3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditorName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatorName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EditTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isIndex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isTop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="pic" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="picSmall" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="pics" Type="System.String" DbType="VarChar(5000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>